### ISSUE TITLE
Bitwise math

### ISSUE THREAD

**Issue by DumbGameMaker** [sam-astro/Astro8-Computer#12]
**Is your feature request related to a problem? Please describe.**
Bitwise math is like the core of binary

**Describe the solution you'd like**
or xor xnor and nand left-shift right-shift etc

**Additional context**

**Comment by sam-astro** [comment]
`and`, `or`, `not`, `bsl` (bit shift left), `bsr` (bit shift right) implemented in dev

**Comment by DumbGameMaker** [comment]
XOR and NAND?

**Comment by sam-astro** [comment]
Those can be created using the other operations; and as of now, all of the possible instructions have been used, so I cannot add any more.
