### ISSUE TITLE
Instruction index strange

### ISSUE THREAD

**Issue by Claupio** [sam-astro/Astro8-Computer#18]
![immagine](https://user-images.githubusercontent.com/46087711/181909492-1b8bdbbc-dc29-4996-8733-f655ef8a5aea.png)
two indexs are equal. And other two indexs are not sequentially

**Comment by GerardSmit** [comment]
This seems to be a mistake in the documentation.

I would reference the source code for all the instructions.

https://github.com/sam-astro/Astro8-Computer/blob/37aeb324e9cb093936737815d9b344ca8d6d17bb/Astro8-Emulator/main.cpp#L125-L151

The index of the array is the index of the instruction:

```cs
int NOP    = 0b00000;
int AIN    = 0b00001;
int BIN    = 0b00010;
int CIN    = 0b00011;
int LDIA   = 0b00100;
int LDIB   = 0b00101;
int RDEXP  = 0b00110;
int WREXP  = 0b00111;
int STA    = 0b01000;
int STC    = 0b01001;
int ADD    = 0b01010;
int SUB    = 0b01011;
int MULT   = 0b01100;
int DIV    = 0b01101;
int JMP    = 0b01110;
int JMPZ   = 0b01111;
int JMPC   = 0b10000;
int LDAIN  = 0b10001;
int STAOUT = 0b10010;
int LDLGE  = 0b10011;
int STLGE  = 0b10100;
int SWP    = 0b10101;
int SWPC   = 0b10110;
int HLT    = 0b10111;
int OUT    = 0b11000;
```
