### ISSUE TITLE
Floating point numbers in Armstrong

### ISSUE THREAD

**Issue by swift502** [sam-astro/Astro8-Computer#19]
**Is your feature request related to a problem? Please describe.**
I'd love to make a raytracing demo, but without floats it seems beyond impractical, and more just impossible.

**Describe the solution you'd like**
Signed fractional numbers with add, sub, mult and div operators. Even very limited precision will do the job, since screen resolution is so small.

**Comment by EmeraldCraft34** [comment]
The 6502 used a decimal flag/mode. Maybe that could be integrated into this in some way?

**Comment by sam-astro** [comment]
A floating point library has been developed in Yabal, as well as a raytracer, see: [https://github.com/sam-astro/A8-Programs-written-in-Yabal/blob/main/raytracer.yabal](https://github.com/sam-astro/A8-Programs-written-in-Yabal/blob/main/raytracer.yabal)
