### ISSUE TITLE
Refine Documentation and Make it More Accurate

### ISSUE THREAD

**Issue by vu1canic** [sam-astro/Astro8-Computer#27]
**Is your feature request related to a problem? Please describe.**
To be honest earlier version of documentation was better, felt less bloated. Everything was on one page, no need to jump through couple pages to find that part you were interested.

**Describe the solution you'd like**
Revert or rework documentation. New documentation feels over the top.

**Comment by sam-astro** [comment]
A lot of work is still yet to be done, I agree. Some more complex things like the instruction set, Armstrong, and hardware are going to take up a lot of space eventually (once all of the information is actually included), so it is necessary to have more than one readme file.

**Comment by sam-astro** [comment]
See new docs:
[https://sam-astro.github.io/Astro8-Computer/](https://sam-astro.github.io/Astro8-Computer/)
