### ISSUE TITLE
Last pixel is black

### ISSUE THREAD

**Issue by maramowicz** [sam-astro/Astro8-Computer#41]
**Describe the bug**
Its not possible to set or see (idk for now) last pixel on emulator on Linux (maybe on windows too but I dont has windows so idk) from version 0.2.0 upwards (0.1.1 works)

**To Reproduce**
1. Open rainbow_gradient.armstrong
2. See error (last pixel is black)

**Expected behavior**
Whole screen is "rainbow"

**Additional context**
Screenshot of bug
![image](https://user-images.githubusercontent.com/29564602/184680242-7a123e60-d0b4-40cf-a596-9c6e69206599.png)

**Comment by maramowicz** [comment]
I think I finded a problem:
For example ADD if result equals/is higher than 65534 subtracting 65534:
562: `if (bus >= 65534)`
But if code want draw pixels, its checking up to 65534:
688: `if (pixelRamIndex >= 65535) {
pixelRamIndex = 61439;`
That means is not possible to set int higher than 65533, so its not possible to set 65534 address.

**Comment by sam-astro** [comment]
Thanks I'll fix this, I accidentally thought 65525 was exclusive haha

**Comment by sam-astro** [comment]
Fixed in the `dev` branch
