### ISSUE TITLE
Add programCounter as a register

### ISSUE THREAD

**Issue by maramowicz** [sam-astro/Astro8-Computer#42]
**Is your feature request related to a problem? Please describe.**
This can much improve jumps in the code, for example we can write programCounter to `@A`, jump to other part of code and after few instructions jump back to address written in `@A`

**Describe the solution you'd like**
I think best name for that register is `@PC`

**Comment by sam-astro** [comment]
In the dev branch you can access the value in the program counter and put it into register A with this:
```c
asm"
pcr
"
```
It isn't implemented as an Armstrong command yet, but I'll consider that in the future.
