### ISSUE TITLE
Bug in documentation (memory layout)

### ISSUE THREAD

**Issue by maramowicz** [sam-astro/Astro8-Computer#45]
In memory layout range of "Variable and General Purpose Memory" is from 16528 to 61439, and range of "Video Memory" form 61439 to 65535
End of VGPM overlaps with begin of VM and (if I calculated it correctly) VGPM end must be 61438.

BTW, I'm noticed this bug on creating arrays for Armstrong, I haven't finished yet but maybe you would be interested ;).

**Comment by sam-astro** [comment]
Fixed
